#!/usr/bin/env python3
"""Generate the frontend config and publish the static site.

config.js is written here rather than committed, because it carries the API
endpoint of whichever account the stack was deployed into. Keeping it out of
git means the repository contains no account-specific values at all.

Usage:
    python3 scripts/publish_frontend.py --stack supplychain --region us-east-1
"""

from __future__ import annotations

import argparse
import json
import mimetypes
import sys
from pathlib import Path

import boto3
from botocore.exceptions import ClientError

ROOT = Path(__file__).resolve().parent.parent
FRONTEND = ROOT / "frontend"
CONFIG_FILE = FRONTEND / "config.js"

# Never published: the example is documentation, and config.js is written
# fresh on every publish.
EXCLUDED = {"config.example.js"}

CONFIG_TEMPLATE = """\
/* Generated by scripts/publish_frontend.py — do not edit or commit. */
window.APP_CONFIG = {config};
"""


def main() -> int:
    args = parse_args()

    outputs = stack_outputs(args.stack, args.region)

    api_endpoint = outputs.get("ApiEndpoint")
    bucket = outputs.get("FrontendBucket")

    if not api_endpoint or not bucket:
        sys.exit("Stack is missing ApiEndpoint or FrontendBucket outputs.")

    write_config(api_endpoint, args)
    upload(bucket, args.region)
    invalidate(args.stack, args.region)

    chat_url = outputs.get("ChatUrl", "")
    print(f"\nPublished. Open {chat_url}")
    print("CloudFront can take a minute to serve the new files.")
    return 0


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stack", required=True)
    parser.add_argument("--region", default="us-east-1")
    parser.add_argument("--enable-vpc", default="false")
    parser.add_argument("--enable-kb", default="true")
    return parser.parse_args()


def stack_outputs(stack: str, region: str) -> dict:
    client = boto3.client("cloudformation", region_name=region)
    try:
        described = client.describe_stacks(StackName=stack)["Stacks"][0]
    except ClientError as exc:
        sys.exit(f"Could not read stack {stack}: {exc}")

    return {
        item["OutputKey"]: item["OutputValue"] for item in described.get("Outputs", [])
    }


def write_config(api_endpoint: str, args: argparse.Namespace) -> None:
    """Write config.js, including which capabilities were actually deployed."""
    config = {
        "apiEndpoint": api_endpoint,
        # The sidebar reports what exists, not what the UI hopes exists. These
        # four are always deployed; the other two follow the cost flags.
        "features": {
            "oauth": True,
            "gateway": True,
            "memory": True,
            "guardrails": True,
            "knowledgeBase": args.enable_kb.lower() == "true",
            "vpc": args.enable_vpc.lower() == "true",
        },
    }

    CONFIG_FILE.write_text(
        CONFIG_TEMPLATE.format(config=json.dumps(config, indent=2))
    )
    print(f"Wrote {CONFIG_FILE.relative_to(ROOT)}")


def upload(bucket: str, region: str) -> None:
    """Upload the site, setting content types and cache headers per file."""
    s3 = boto3.client("s3", region_name=region)

    print(f"Publishing to s3://{bucket}/")
    for path in sorted(FRONTEND.iterdir()):
        if not path.is_file() or path.name in EXCLUDED:
            continue

        content_type = mimetypes.guess_type(path.name)[0] or "application/octet-stream"

        # index.html and config.js must never be cached: a stale index or a
        # stale API endpoint survives every redeploy otherwise. The static
        # assets are safe to cache because the whole site is republished at
        # once and CloudFront is invalidated below.
        volatile = path.name in {"index.html", "config.js"}
        cache_control = "no-cache, must-revalidate" if volatile else "max-age=300"

        s3.upload_file(
            str(path),
            bucket,
            path.name,
            ExtraArgs={"ContentType": content_type, "CacheControl": cache_control},
        )
        print(f"  {path.name}")


def invalidate(stack: str, region: str) -> None:
    """Clear the CloudFront cache so the new files are served immediately."""
    outputs = stack_outputs(stack, region)
    distribution_id = outputs.get("DistributionId")

    if not distribution_id:
        # DistributionId is exported by the frontend stack but not surfaced at
        # the root, so this is informational rather than a failure.
        print("\nNo DistributionId output — skipping cache invalidation.")
        return

    cloudfront = boto3.client("cloudfront")
    cloudfront.create_invalidation(
        DistributionId=distribution_id,
        InvalidationBatch={
            "Paths": {"Quantity": 1, "Items": ["/*"]},
            "CallerReference": str(__import__("time").time()),
        },
    )
    print("Cache invalidation requested")


if __name__ == "__main__":
    sys.exit(main())
